### ISSUE TITLE
下载的软件打不开

### ISSUE THREAD

**Issue by xiaoqi2020** [zhanggaolei001/JdLoginTool#2]
双击或者右键打开都没反应！

**Comment by zhanggaolei001** [comment]
需要安装两个.net core运行环境,Readme中有连接

**Comment by xiaoqi2020** [comment]
> 需要安装两个.net core运行环境,Readme中有连接

不好意思，英语不好，实在没找到连接在哪！如果可以的话，能否发一下呢？谢谢

**Comment by zhanggaolei001** [comment]
项目主页,阅读"须知"一栏



***@***.***
 
发件人： xiaoqi2020
发送时间： 2021-09-08 13:48
收件人： zhanggaolei001/JdLoginTool
抄送： zhanggaolei001; Comment
主题： Re: [zhanggaolei001/JdLoginTool] 下载的软件打不开 (#2)
需要安装两个.net core运行环境,Readme中有连接
不好意思，英语不好，实在没找到连接在哪！如果可以的话，能否发一下呢？谢谢
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
